//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYS.Application.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPYSEntities : DbContext
    {
        public DbPYSEntities()
            : base("name=DbPYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SysAdresTipleri> SysAdresTipleri { get; set; }
        public virtual DbSet<SysUnvanlar> SysUnvanlar { get; set; }
        public virtual DbSet<TblKisi> TblKisi { get; set; }
        public virtual DbSet<TblKisiIletisim> TblKisiIletisim { get; set; }
        public virtual DbSet<TblKullanicilar> TblKullanicilar { get; set; }
        public virtual DbSet<VwKisiKullaniciIletisim> VwKisiKullaniciIletisim { get; set; }
        public virtual DbSet<TblFirmalar> TblFirmalar { get; set; }
        public virtual DbSet<TblKisiFirma> TblKisiFirma { get; set; }
        public virtual DbSet<VwFirmalar> VwFirmalar { get; set; }
    }
}
